<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
    <PackageReference Include="MailKit" Version="4.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskPilot.DTOs\TaskPilot.DTOs.csproj" />
    <ProjectReference Include="..\TaskPilot.Models\TaskPilot.Models.csproj" />
    <ProjectReference Include="..\TaskPilot.Services\TaskPilot.Services.csproj" />
  </ItemGroup>

</Project>
